name: cd

on:
  push:
    branches:
      - master
      - content_fixes
      - furkan-logo

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: create .env file
        run: touch .env

      - name: Add recaptcha key
        run: echo "SITE_RECAPTCHA_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" >> .env

      - name: Add recaptcha secret
        run: echo "SITE_RECAPTCHA_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" >> .env

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

